name: Collect VLESS Configs

on:
  schedule:
    - cron: '0 */1 * * *'
  workflow_dispatch:  # Ручной запуск

jobs:
  collect:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install requests

      - name: Run collector (ALL)
        run: python collect.py -f subscriptions.txt -o ALL.json

      - name: Run collector (ALL NORU)
        run: python collect.py -f subscriptions.txt -o ALL-NORU.json --require-remark --exclude-flags RU
        
      - name: Run collector (NL ONLY)
        run: python collect.py -f subscriptions.txt -o NL.json --require-remark --include-flags NL

      - name: Run collector (SG ONLY)
        run: python collect.py -f subscriptions.txt -o SG.json --require-remark --include-flags SG

      - name: Run collector (US ONLY)
        run: python collect.py -f subscriptions.txt -o US.json --require-remark --include-flags US
        
      - name: Run collector (SE ONLY)
        run: python collect.py -f subscriptions.txt -o SE.json --require-remark --include-flags SE


      - name: Commit and push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          
          git add ALL.json ALL-NORU.json NL.json
          
          # Коммитим только если файл изменился
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Update VLESS balancer config — $(date -u '+%Y-%m-%d %H:%M UTC')"
            git push
          fi
          
